openapi: 3.0.0
info:
  version: 1.0.0
  title: Ravimoshark Client API
  termsOfService: 'https://ravimoshark.com/terms/'
  contact:
    email: dev@ravimoshark.com
    url: 'http://ravimoshark.com/contact'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  description: >
    This is an API to interact with Ravimoshark client database.

    # Introduction

    This API allow to create, modify and delete addresses and clients.

    # User Authentication

    This API does not contain any kind of user validation but It request to have
    a valid authentication user to interact with it.
    For more information about user Authentication, please refer to
    [Ravimoshark User Authentication](https://ravimoshark.com/back/apis/auth/latest).
externalDocs:
  description: Find out how to interact with Ravimoshark's APIs.
  url: 'https://ravimoshark.com/back/apis/auth/latest'
tags:
  - name: Addresses
    description: Operations about addresses.
  - name: Clients
    description: Operations about clients.
servers:
  - url: 'http://localhost:8002'
  - url: 'https://ravimoshark.com/back/apis/client/v1'
  - url: 'https://ravimoshark.com/back/apis/client/latest'
